export const UsersData = {
  employees: [
    {
      id: "emp1",
      email: "emp1@example.com",
      password: "123",
      fullName: "John Doe",
      taskCounts: {
        new: 1,
        completed: 1,
        accepted: 2,
        failed: 1,
      },
      tasks: [
        {
          id: "task1",
          title: "Design new UI",
          description:
            "Create a modern and user-friendly interface for the application",
          status: "completed",
          postDate: "2024-10-08T09:00:00",
          dueDate: "2024-10-15T17:00:00",
          priority: "high",
          estimatedHours: 8,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp1", empName: "John Doe" },
        },
        {
          id: "task2",
          title: "Develop new feature",
          description:
            "Implement a new functionality to enhance user experience",
          status: "accepted",
          postDate: "2024-10-10T14:30:00",
          dueDate: "2024-10-20T18:00:00",
          priority: "medium",
          estimatedHours: 12,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp1", empName: "John Doe" },
        },
        {
          id: "task10",
          title: "Refactor codebase",
          description:
            "Improve code structure and readability for better maintainability",
          status: "accepted",
          postDate: "2024-10-15T11:00:00",
          dueDate: "2024-10-22T17:00:00",
          priority: "medium",
          estimatedHours: 10,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp1", empName: "John Doe" },
        },
        {
          id: "task15",
          title: "Update user interface",
          description:
            "Refresh the UI components to align with the latest design guidelines",
          status: "new",
          postDate: "2024-10-21T10:00:00",
          dueDate: "2024-10-28T17:00:00",
          priority: "medium",
          estimatedHours: 5,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
          assignedBy: "admin1",
          assignedTo: { empId: "emp1", empName: "John Doe" },
        },
        {
          id: "task16",
          title: "Fix navigation bug",
          description:
            "Resolve issues with the navigation menu to ensure smooth user experience",
          status: "failed",
          postDate: "2024-10-09T09:30:00",
          dueDate: "2024-10-11T17:00:00",
          priority: "high",
          estimatedHours: 3,
          accepted: true,
          completed: false,
          failed: true,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp1", empName: "John Doe" },
        },
      ],
    },
    {
      id: "emp2",
      email: "emp2@example.com",
      password: "123",
      fullName: "Jane Smith",
      taskCounts: {
        new: 1,
        completed: 0,
        accepted: 1,
        failed: 1,
      },
      tasks: [
        {
          id: "task3",
          title: "Implement payment gateway",
          description:
            "Integrate a secure payment system for online transactions",
          status: "failed",
          postDate: "2024-10-03T08:00:00",
          dueDate: "2024-10-10T17:00:00",
          priority: "high",
          estimatedHours: 16,
          accepted: true,
          completed: false,
          failed: true,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp2", empName: "Jane Smith" },
        },
        {
          id: "task4",
          title: "Create user authentication",
          description:
            "Develop a robust authentication system for user accounts",
          status: "new",
          postDate: "2024-10-18T13:00:00",
          dueDate: "2024-10-25T17:00:00",
          priority: "medium",
          estimatedHours: 10,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
          assignedBy: "admin1",
          assignedTo: { empId: "emp2", empName: "Jane Smith" },
        },
        {
          id: "task11",
          title: "Setup CI/CD pipeline",
          description:
            "Establish an automated deployment process for efficient development",
          status: "accepted",
          postDate: "2024-10-12T09:00:00",
          dueDate: "2024-10-19T17:00:00",
          priority: "high",
          estimatedHours: 8,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp2", empName: "Jane Smith" },
        },
      ],
    },
    {
      id: "emp3",
      email: "emp3@example.com",
      password: "123",
      fullName: "Alice Johnson",
      taskCounts: {
        new: 0,
        completed: 0,
        accepted: 2,
        failed: 0,
      },
      tasks: [
        {
          id: "task7",
          title: "Optimize database queries",
          description: "Improve database performance by optimizing SQL queries",
          status: "accepted",
          postDate: "2024-10-11T10:00:00",
          dueDate: "2024-10-18T17:00:00",
          priority: "high",
          estimatedHours: 6,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp3", empName: "Alice Johnson" },
        },
        {
          id: "task12",
          title: "Implement caching layer",
          description:
            "Add a caching mechanism to reduce database load and improve response times",
          status: "accepted",
          postDate: "2024-10-14T09:30:00",
          dueDate: "2024-10-21T17:00:00",
          priority: "high",
          estimatedHours: 12,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp3", empName: "Alice Johnson" },
        },
      ],
    },
    {
      id: "emp4",
      email: "emp4@example.com",
      password: "123",
      fullName: "Bob Brown",
      taskCounts: {
        new: 1,
        completed: 1,
        accepted: 0,
        failed: 0,
      },
      tasks: [
        {
          id: "task8",
          title: "Write API documentation",
          description:
            "Create comprehensive documentation for the application's API endpoints",
          status: "new",
          postDate: "2024-10-15T11:00:00",
          dueDate: "2024-10-22T17:00:00",
          priority: "medium",
          estimatedHours: 4,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
          assignedBy: "admin1",
          assignedTo: { empId: "emp4", empName: "Bob Brown" },
        },
        {
          id: "task13",
          title: "Create user onboarding flow",
          description:
            "Design and implement a smooth onboarding process for new users",
          status: "completed",
          postDate: "2024-10-17T09:00:00",
          dueDate: "2024-10-24T17:00:00",
          priority: "medium",
          estimatedHours: 6,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp4", empName: "Bob Brown" },
        },
      ],
    },
    {
      id: "emp5",
      email: "emp5@example.com",
      password: "123",
      fullName: "Charlie Davis",
      taskCounts: {
        new: 0,
        completed: 2,
        accepted: 0,
        failed: 0,
      },
      tasks: [
        {
          id: "task9",
          title: "Fix login bug",
          description:
            "Resolve issues preventing users from logging in successfully",
          status: "completed",
          postDate: "2024-10-05T14:00:00",
          dueDate: "2024-10-12T17:00:00",
          priority: "high",
          estimatedHours: 3,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp5", empName: "Charlie Davis" },
        },
        {
          id: "task14",
          title: "Implement error tracking",
          description:
            "Set up a system to monitor and log application errors for quick resolution",
          status: "completed",
          postDate: "2024-10-07T10:30:00",
          dueDate: "2024-10-14T17:00:00",
          priority: "high",
          estimatedHours: 5,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
          assignedTo: { empId: "emp5", empName: "Charlie Davis" },
        },
      ],
    },
  ],
  admin: {
    id: "admin1",
    email: "admin@1",
    password: "123",
    fullName: "Admin User",
    employeesCount: 5,
    activeTasks: 5,
    completedTasks: 4,
    pendingReviews: 2,
    tasks: [
      {
        id: "task1",
        title: "Design new UI",
        description:
          "Create a modern and user-friendly interface for the application",
        status: "completed",
        postDate: "2024-10-08T09:00:00",
        dueDate: "2024-10-15T17:00:00",
        priority: "high",
        estimatedHours: 8,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedTo: { empId: "emp1", empName: "John Doe" },
      },
      {
        id: "task2",
        title: "Develop new feature",
        description: "Implement a new functionality to enhance user experience",
        status: "accepted",
        postDate: "2024-10-10T14:30:00",
        dueDate: "2024-10-20T18:00:00",
        priority: "medium",
        estimatedHours: 12,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: { empId: "emp1", empName: "John Doe" },
      },
      {
        id: "task3",
        title: "Implement payment gateway",
        description:
          "Integrate a secure payment system for online transactions",
        status: "failed",
        postDate: "2024-10-03T08:00:00",
        dueDate: "2024-10-10T17:00:00",
        priority: "high",
        estimatedHours: 16,
        accepted: true,
        completed: false,
        failed: true,
        new: false,
        assignedTo: { empId: "emp2", empName: "Jane Smith" },
      },
      {
        id: "task4",
        title: "Create user authentication",
        description: "Develop a robust authentication system for user accounts",
        status: "new",
        postDate: "2024-10-18T13:00:00",
        dueDate: "2024-10-25T17:00:00",
        priority: "medium",
        estimatedHours: 10,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
        assignedTo: { empId: "emp2", empName: "Jane Smith" },
      },
      {
        id: "task7",
        title: "Optimize database queries",
        description: "Improve database performance by optimizing SQL queries",
        status: "accepted",
        postDate: "2024-10-11T10:00:00",
        dueDate: "2024-10-18T17:00:00",
        priority: "high",
        estimatedHours: 6,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: { empId: "emp3", empName: "Alice Johnson" },
      },
      {
        id: "task8",
        title: "Write API documentation",
        description:
          "Create comprehensive documentation for the application's API endpoints",
        status: "new",
        postDate: "2024-10-15T11:00:00",
        dueDate: "2024-10-22T17:00:00",
        priority: "medium",
        estimatedHours: 4,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
        assignedTo: { empId: "emp4", empName: "Bob Brown" },
      },
      {
        id: "task9",
        title: "Fix login bug",
        description:
          "Resolve issues preventing users from logging in successfully",
        status: "completed",
        postDate: "2024-10-05T14:00:00",
        dueDate: "2024-10-12T17:00:00",
        priority: "high",
        estimatedHours: 3,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedTo: { empId: "emp5", empName: "Charlie Davis" },
      },
      {
        id: "task10",
        title: "Refactor codebase",
        description:
          "Improve code structure and readability for better maintainability",
        status: "accepted",
        postDate: "2024-10-15T11:00:00",
        dueDate: "2024-10-22T17:00:00",
        priority: "medium",
        estimatedHours: 10,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: { empId: "emp1", empName: "John Doe" },
      },
      {
        id: "task11",
        title: "Setup CI/CD pipeline",
        description:
          "Establish an automated deployment process for efficient development",
        status: "accepted",
        postDate: "2024-10-12T09:00:00",
        dueDate: "2024-10-19T17:00:00",
        priority: "high",
        estimatedHours: 8,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: { empId: "emp2", empName: "Jane Smith" },
      },
      {
        id: "task12",
        title: "Implement caching layer",
        description:
          "Add a caching mechanism to reduce database load and improve response times",
        status: "accepted",
        postDate: "2024-10-14T10:00:00",
        dueDate: "2024-10-21T17:00:00",
        priority: "high",
        estimatedHours: 12,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: { empId: "emp3", empName: "Alice Johnson" },
      },
      {
        id: "task13",
        title: "Create user onboarding flow",
        description:
          "Design and implement a smooth onboarding process for new users",
        status: "completed",
        postDate: "2024-10-17T09:30:00",
        dueDate: "2024-10-24T17:00:00",
        priority: "medium",
        estimatedHours: 6,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedTo: { empId: "emp4", empName: "Bob Brown" },
      },
      {
        id: "task14",
        title: "Implement error tracking",
        description:
          "Set up a system to monitor and log application errors for quick resolution",
        status: "completed",
        postDate: "2024-10-07T11:15:00",
        dueDate: "2024-10-14T17:00:00",
        priority: "high",
        estimatedHours: 5,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedTo: { empId: "emp5", empName: "Charlie Davis" },
      },
      {
        id: "task15",
        title: "Update user interface",
        description:
          "Refresh the UI components to align with the latest design guidelines",
        status: "new",
        postDate: "2024-10-21T14:45:00",
        dueDate: "2024-10-28T17:00:00",
        priority: "medium",
        estimatedHours: 5,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
        assignedTo: { empId: "emp1", empName: "John Doe" },
      },
      {
        id: "task16",
        title: "Fix navigation bug",
        description:
          "Resolve issues with the navigation menu to ensure smooth user experience",
        status: "failed",
        postDate: "2024-10-21T16:30:00",
        dueDate: "2024-10-28T17:00:00",
        priority: "medium",
        estimatedHours: 5,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
        assignedTo: { empId: "emp1", empName: "John Doe" },
      },
    ],
  },
};
export default UsersData;
