export const UsersData = {
  employees: [
    {
      id: "emp1",
      email: "emp1@example.com",
      password: "123",
      fullName: "John Doe",
      tasks: [
        {
          id: "task1",
          title: "Design new UI",
          status: "completed",
          dueDate: "2023-10-15",
          priority: "high",
          estimatedHours: 8,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
        },
        {
          id: "task2",
          title: "Develop new feature",
          status: "accepted",
          dueDate: "2023-10-20",
          priority: "medium",
          estimatedHours: 12,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
        },
      ],
    },
    {
      id: "emp2",
      email: "emp2@example.com",
      password: "123",
      fullName: "Jane Smith",
      tasks: [
        {
          id: "task3",
          title: "Implement payment gateway",
          status: "failed",
          dueDate: "2023-10-10",
          priority: "high",
          estimatedHours: 16,
          accepted: true,
          completed: false,
          failed: true,
          new: false,
        },
        {
          id: "task4",
          title: "Create user authentication",
          status: "new",
          dueDate: "2023-10-25",
          priority: "medium",
          estimatedHours: 10,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
        },
      ],
    },
    {
      id: "emp3",
      email: "emp3@example.com",
      password: "123",
      fullName: "Alice Johnson",
      tasks: [
        {
          id: "task7",
          title: "Optimize database queries",
          status: "accepted",
          dueDate: "2023-10-18",
          priority: "high",
          estimatedHours: 6,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
        },
      ],
    },
    {
      id: "emp4",
      email: "emp4@example.com",
      password: "123",
      fullName: "Bob Brown",
      tasks: [
        {
          id: "task8",
          title: "Write API documentation",
          status: "new",
          dueDate: "2023-10-22",
          priority: "medium",
          estimatedHours: 4,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
        },
      ],
    },
    {
      id: "emp5",
      email: "emp5@example.com",
      password: "123",
      fullName: "Charlie Davis",
      tasks: [
        {
          id: "task9",
          title: "Fix login bug",
          status: "completed",
          dueDate: "2023-10-12",
          priority: "high",
          estimatedHours: 3,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
        },
      ],
    },
  ],
  admin: {
    id: "admin1",
    email: "admin@1",
    password: "123",
    fullName: "Admin User",
    tasks: [
      {
        id: "task5",
        title: "Review employee performance",
        status: "new",
        dueDate: "2023-10-30",
        priority: "high",
        estimatedHours: 6,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
      },
      {
        id: "task6",
        title: "Prepare quarterly report",
        status: "accepted",
        dueDate: "2023-11-05",
        priority: "medium",
        estimatedHours: 8,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
      },
      {
        id: "task10",
        title: "Organize team building",
        status: "completed",
        dueDate: "2023-10-28",
        priority: "low",
        estimatedHours: 4,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
      },
      {
        id: "task11",
        title: "Update company policies",
        status: "failed",
        dueDate: "2023-10-20",
        priority: "medium",
        estimatedHours: 5,
        accepted: true,
        completed: false,
        failed: true,
        new: false,
      },
    ],
  },
};

export default UsersData;
