export const UsersData = {
  employees: [
    {
      id: "emp1",
      email: "emp1@example.com",
      password: "123",
      fullName: "John Doe",
      taskCounts: {
        new: 1,
        completed: 1,
        accepted: 2,
        failed: 1
      },
      tasks: [
        {
          id: "task1",
          title: "Design new UI",
          status: "completed",
          dueDate: "2023-10-15",
          priority: "high",
          estimatedHours: 8,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
        {
          id: "task2",
          title: "Develop new feature",
          status: "accepted",
          dueDate: "2023-10-20",
          priority: "medium",
          estimatedHours: 12,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
        {
          id: "task10",
          title: "Refactor codebase",
          status: "accepted",
          dueDate: "2023-10-22",
          priority: "medium",
          estimatedHours: 10,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
        {
          id: "task15",
          title: "Update user interface",
          status: "new",
          dueDate: "2023-10-28",
          priority: "medium",
          estimatedHours: 5,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
          assignedBy: "admin1",
        },
        {
          id: "task16",
          title: "Fix navigation bug",
          status: "failed",
          dueDate: "2023-10-11",
          priority: "high",
          estimatedHours: 3,
          accepted: true,
          completed: false,
          failed: true,
          new: false,
          assignedBy: "admin1",
        },
      ],
    },
    {
      id: "emp2",
      email: "emp2@example.com",
      password: "123",
      fullName: "Jane Smith",
      taskCounts: {
        new: 1,
        completed: 0,
        accepted: 1,
        failed: 1
      },
      tasks: [
        {
          id: "task3",
          title: "Implement payment gateway",
          status: "failed",
          dueDate: "2023-10-10",
          priority: "high",
          estimatedHours: 16,
          accepted: true,
          completed: false,
          failed: true,
          new: false,
          assignedBy: "admin1",
        },
        {
          id: "task4",
          title: "Create user authentication",
          status: "new",
          dueDate: "2023-10-25",
          priority: "medium",
          estimatedHours: 10,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
          assignedBy: "admin1",
        },
        {
          id: "task11",
          title: "Setup CI/CD pipeline",
          status: "accepted",
          dueDate: "2023-10-19",
          priority: "high",
          estimatedHours: 8,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
      ],
    },
    {
      id: "emp3",
      email: "emp3@example.com",
      password: "123",
      fullName: "Alice Johnson",
      taskCounts: {
        new: 0,
        completed: 0,
        accepted: 2,
        failed: 0
      },
      tasks: [
        {
          id: "task7",
          title: "Optimize database queries",
          status: "accepted",
          dueDate: "2023-10-18",
          priority: "high",
          estimatedHours: 6,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
        {
          id: "task12",
          title: "Implement caching layer",
          status: "accepted",
          dueDate: "2023-10-21",
          priority: "high",
          estimatedHours: 12,
          accepted: true,
          completed: false,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
      ],
    },
    {
      id: "emp4",
      email: "emp4@example.com",
      password: "123",
      fullName: "Bob Brown",
      taskCounts: {
        new: 1,
        completed: 1,
        accepted: 0,
        failed: 0
      },
      tasks: [
        {
          id: "task8",
          title: "Write API documentation",
          status: "new",
          dueDate: "2023-10-22",
          priority: "medium",
          estimatedHours: 4,
          accepted: false,
          completed: false,
          failed: false,
          new: true,
          assignedBy: "admin1",
        },
        {
          id: "task13",
          title: "Create user onboarding flow",
          status: "completed",
          dueDate: "2023-10-24",
          priority: "medium",
          estimatedHours: 6,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
      ],
    },
    {
      id: "emp5",
      email: "emp5@example.com",
      password: "123",
      fullName: "Charlie Davis",
      taskCounts: {
        new: 0,
        completed: 2,
        accepted: 0,
        failed: 0
      },
      tasks: [
        {
          id: "task9",
          title: "Fix login bug",
          status: "completed",
          dueDate: "2023-10-12",
          priority: "high",
          estimatedHours: 3,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
        {
          id: "task14",
          title: "Implement error tracking",
          status: "completed",
          dueDate: "2023-10-14",
          priority: "high",
          estimatedHours: 5,
          accepted: true,
          completed: true,
          failed: false,
          new: false,
          assignedBy: "admin1",
        },
      ],
    },
  ],
  admin: {
    id: "admin1",
    email: "admin@1",
    password: "123",
    fullName: "Admin User",
    employeesCount: 5,
    activeTasks: 7,
    completedTasks: 3,
    pendingReviews: 2,
    tasks: [
      {
        id: "task1",
        title: "Design new UI",
        status: "completed",
        dueDate: "2023-10-15",
        priority: "high",
        estimatedHours: 8,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedTo: "emp1",
      },
      {
        id: "task2",
        title: "Develop new feature",
        status: "accepted",
        dueDate: "2023-10-20",
        priority: "medium",
        estimatedHours: 12,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: "emp1",
      },
      {
        id: "task3",
        title: "Implement payment gateway",
        status: "failed",
        dueDate: "2023-10-10",
        priority: "high",
        estimatedHours: 16,
        accepted: true,
        completed: false,
        failed: true,
        new: false,
        assignedTo: "emp2",
      },
      {
        id: "task4",
        title: "Create user authentication",
        status: "new",
        dueDate: "2023-10-25",
        priority: "medium",
        estimatedHours: 10,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
        assignedTo: "emp2",
      },
      {
        id: "task7",
        title: "Optimize database queries",
        status: "accepted",
        dueDate: "2023-10-18",
        priority: "high",
        estimatedHours: 6,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: "emp3",
      },
      {
        id: "task8",
        title: "Write API documentation",
        status: "new",
        dueDate: "2023-10-22",
        priority: "medium",
        estimatedHours: 4,
        accepted: false,
        completed: false,
        failed: false,
        new: true,
        assignedTo: "emp4",
      },
      {
        id: "task9",
        title: "Fix login bug",
        status: "completed",
        dueDate: "2023-10-12",
        priority: "high",
        estimatedHours: 3,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedTo: "emp5",
      },
      {
        id: "task10",
        title: "Refactor codebase",
        status: "accepted",
        dueDate: "2023-10-22",
        priority: "medium",
        estimatedHours: 10,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: "emp1",
      },
      {
        id: "task11",
        title: "Setup CI/CD pipeline",
        status: "accepted",
        dueDate: "2023-10-19",
        priority: "high",
        estimatedHours: 8,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: "emp2",
      },
      {
        id: "task12",
        title: "Implement caching layer",
        status: "accepted",
        dueDate: "2023-10-21",
        priority: "high",
        estimatedHours: 12,
        accepted: true,
        completed: false,
        failed: false,
        new: false,
        assignedTo: "emp3",
      },
      {
        id: "task13",
        title: "Create user onboarding flow",
        status: "completed",
        dueDate: "2023-10-24",
        priority: "medium",
        estimatedHours: 6,
        accepted: true,
        completed: true,
        failed: false,
        new: false,
        assignedBy: "admin1",
      },
    ],
  },
};

export default UsersData;
